# dans netlify.toml

# On spécifie uniquement le dossier de publication.
# Le plugin s'occupera de la commande de build.
[build]
  publish = ".next"

# On garde le plugin essentiel pour Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"
