# dans netlify.toml

# On laisse le plugin Next.js gérer entièrement le build.
# Il est assez intelligent pour lancer "npm run build" et trouver le dossier ".next" tout seul.
[[plugins]]
  package = "@netlify/plugin-nextjs"
